[workspace]
members = ["crates/nexus-webfont-core", "crates/nexus-webfont-cli"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/vsjov/nexus-webfont-converter"
rust-version = "1.89"
version = "1.2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
oxifont-webfont = { version = "0.2.0", default-features = false, features = [
  "woff1",
  "woff2",
] }
rayon = "1.10.0"
thiserror = "2.0.18"
walkdir = "2.5.0"
